[project]
name = "comfyui-rvc"
description = "a comfyui custom node for [a/Retrieval-based-Voice-Conversion-WebUI](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI.git), you can Voice-Conversion in comfyui now!\nNOTE: make sure ffmpeg is worked in your commandline for Linux"
version = "1.0.0"
license = "LICENSE"
dependencies = ["joblib>=1.1.0", "numba", "numpy==1.23.5", "scipy", "librosa==0.9.1", "llvmlite", "fairseq", "faiss-cpu", "Cython", "pydub>=0.25.1", "soundfile>=0.12.1", "ffmpeg-python>=0.2.0", "tensorboardX", "Jinja2>=3.1.2", "json5", "Markdown", "matplotlib>=3.7.0", "matplotlib-inline>=0.1.3", "praat-parselmouth>=0.4.2", "Pillow>=9.1.1", "resampy>=0.4.2", "scikit-learn", "tensorboard", "tqdm>=4.63.1", "tornado>=6.1", "Werkzeug>=2.2.3", "uc-micro-py>=1.0.1", "sympy>=1.11.1", "tabulate>=0.8.10", "PyYAML>=6.0", "pyasn1>=0.4.8", "pyasn1-modules>=0.2.8", "fsspec>=2022.11.0", "absl-py>=1.2.0", "audioread", "uvicorn>=0.21.1", "colorama>=0.4.5", "pyworld==0.3.2", "httpx", "onnxruntime; sys_platform == 'darwin'", "onnxruntime-gpu; sys_platform != 'darwin'", "torchcrepe==0.0.20", "fastapi", "torchfcpe", "ffmpy==0.3.1", "python-dotenv>=1.0.0", "av"]

[project.urls]
Repository = "https://github.com/AIFSH/ComfyUI-RVC"
#  Used by Comfy Registry https://comfyregistry.org

[tool.comfy]
PublisherId = ""
DisplayName = "ComfyUI-RVC"
Icon = ""
